"""exp-6.21 — Population-level Turing test.

Hypothesis: A complete persona set passes the population Turing test >= 70%
of the time — LLM judges believe the set represents real customers.

Approach:
  1. Fetch + segment + synthesize personas from ALL clusters.
  2. Present the FULL SET to 10 independent LLM judges.
  3. Each judge answers: real/AI-generated/unsure, coverage %, authenticity 1-5.
  4. Compute Turing pass rate, mean perceived coverage, mean authenticity.

Usage:
    python scripts/run_exp_6_21.py
"""

from __future__ import annotations

import asyncio
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "crawler"))
sys.path.insert(0, str(REPO_ROOT / "segmentation"))
sys.path.insert(0, str(REPO_ROOT / "synthesis"))
sys.path.insert(0, str(REPO_ROOT / "orchestration"))
sys.path.insert(0, str(REPO_ROOT / "twin"))
sys.path.insert(0, str(REPO_ROOT / "evals"))

from dotenv import load_dotenv

load_dotenv(REPO_ROOT / "synthesis" / ".env")

from anthropic import AsyncAnthropic  # noqa: E402

from crawler import fetch_all  # noqa: E402
from segmentation.models.record import RawRecord  # noqa: E402
from segmentation.pipeline import segment  # noqa: E402
from synthesis.config import settings  # noqa: E402
from synthesis.engine.model_backend import AnthropicBackend  # noqa: E402
from synthesis.engine.synthesizer import SynthesisError, synthesize  # noqa: E402
from synthesis.models.cluster import ClusterData  # noqa: E402

TENANT_ID = "tenant_acme_corp"
TENANT_INDUSTRY = "B2B SaaS"
TENANT_PRODUCT = "Project management tool for engineering teams"

OUTPUT_DIR = REPO_ROOT / "output" / "experiments" / "exp-6.21"

N_RATERS = 10


# ---------------------------------------------------------------------------
# Judge function
# ---------------------------------------------------------------------------

async def judge_population(
    personas: list[dict],
    client: AsyncAnthropic,
    model: str,
    rater_id: int,
) -> dict:
    """One simulated rater judges the full persona set."""
    persona_cards = []
    for i, p in enumerate(personas):
        card = f"""### Persona {i + 1}: {p.get('name')}
Summary: {p.get('summary')}
Goals: {', '.join(p.get('goals', [])[:3])}
Pains: {', '.join(p.get('pains', [])[:3])}
Vocabulary: {', '.join(p.get('vocabulary', [])[:5])}
Sample quote: "{p.get('sample_quotes', [''])[0]}"
"""
        persona_cards.append(card)

    all_cards = "\n".join(persona_cards)

    prompt = f"""You are Evaluator #{rater_id} reviewing a set of customer personas for a B2B SaaS company that makes project management tools for engineering teams.

Below is the complete persona set. These personas were either (A) created from real customer behavioral data, or (B) generated by an AI system.

{all_cards}

Answer these three questions:

1. Does this set represent a real company's customer base, or was it AI-generated? Answer: "real", "AI-generated", or "unsure"
2. What percentage of a real customer base for this type of product does this set appear to cover? (0-100)
3. Rate the overall authenticity of this persona set (1-5, where 5 = completely believable as real customers)

Respond with STRICT JSON only:
{{"verdict": "real" or "AI-generated" or "unsure", "coverage_pct": <int 0-100>, "authenticity": <int 1-5>, "rationale": "<2-3 sentences>"}}"""

    resp = await client.messages.create(
        model=model,
        max_tokens=300,
        temperature=0.8,
        messages=[{"role": "user", "content": prompt}],
    )
    text = next(b.text for b in resp.content if b.type == "text")
    match = re.search(r"\{.*\}", text, re.DOTALL)
    return json.loads(match.group(0)) if match else {}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main() -> None:
    print("=" * 72)
    print("exp-6.21 — Population-level Turing test")
    print("=" * 72)

    if not settings.anthropic_api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not set in synthesis/.env")

    client = AsyncAnthropic(api_key=settings.anthropic_api_key)
    backend = AnthropicBackend(client=client, model=settings.default_model)
    model = settings.default_model

    # ---- Step 1: Fetch + segment + synthesize ----
    print("\n[1/3] Fetching and segmenting records...")
    raw_records = fetch_all(TENANT_ID)
    records = [RawRecord.model_validate(r.model_dump()) for r in raw_records]

    cluster_dicts = segment(
        records,
        tenant_industry=TENANT_INDUSTRY,
        tenant_product=TENANT_PRODUCT,
        existing_persona_names=[],
        similarity_threshold=0.15,
        min_cluster_size=2,
    )
    clusters = sorted(
        [ClusterData.model_validate(c) for c in cluster_dicts],
        key=lambda c: c.cluster_id,
    )
    print(f"  Got {len(clusters)} clusters: {[c.cluster_id for c in clusters]}")

    print("\n  Synthesizing personas from all clusters...")
    persona_results = []
    for i, cluster in enumerate(clusters):
        print(f"  [{i + 1}/{len(clusters)}] {cluster.cluster_id}...")
        try:
            r = await synthesize(cluster, backend)
            p_dict = r.persona.model_dump(mode="json")
            persona_results.append({
                "cluster_id": cluster.cluster_id,
                "status": "ok",
                "persona": p_dict,
                "cost_usd": r.total_cost_usd,
                "groundedness": r.groundedness.score,
            })
            print(
                f"    [OK] {p_dict['name']}  "
                f"cost=${r.total_cost_usd:.4f}  "
                f"grounded={r.groundedness.score:.2f}"
            )
        except SynthesisError as e:
            total_cost = sum(a.cost_usd for a in e.attempts)
            persona_results.append({
                "cluster_id": cluster.cluster_id,
                "status": "failed",
                "error": str(e),
                "cost_usd": total_cost,
            })
            print(f"    [FAIL] {e}  cost=${total_cost:.4f}")

    ok_results = [r for r in persona_results if r["status"] == "ok"]
    if not ok_results:
        raise RuntimeError("No personas synthesized successfully")
    personas = [r["persona"] for r in ok_results]
    print(f"\n  {len(personas)} personas synthesized successfully")

    # ---- Step 2: Run population judges ----
    print(f"\n[2/3] Running {N_RATERS} population-level judges...")
    tasks = [
        judge_population(personas, client, model, rid)
        for rid in range(1, N_RATERS + 1)
    ]
    judgments = await asyncio.gather(*tasks)
    valid_judgments = [j for j in judgments if j]
    print(f"  Got {len(valid_judgments)}/{N_RATERS} valid judgments")

    for j in valid_judgments:
        print(
            f"    verdict={j.get('verdict'):15s}  "
            f"coverage={j.get('coverage_pct', '?')}%  "
            f"auth={j.get('authenticity', '?')}  "
            f"rationale={j.get('rationale', '')[:80]}..."
        )

    # ---- Step 3: Compute metrics ----
    print("\n[3/3] Computing metrics...")

    # Turing pass rate: % of judges who said "real"
    n_real = sum(1 for j in valid_judgments if j.get("verdict") == "real")
    n_unsure = sum(1 for j in valid_judgments if j.get("verdict") == "unsure")
    n_ai = sum(1 for j in valid_judgments if j.get("verdict") == "AI-generated")
    turing_pass_rate = (n_real / len(valid_judgments) * 100) if valid_judgments else 0

    # Mean perceived coverage
    coverages = [j.get("coverage_pct", 0) for j in valid_judgments if "coverage_pct" in j]
    mean_coverage = sum(coverages) / len(coverages) if coverages else 0

    # Mean authenticity
    auths = [j.get("authenticity", 0) for j in valid_judgments if "authenticity" in j]
    mean_authenticity = sum(auths) / len(auths) if auths else 0

    hypothesis_pass = turing_pass_rate >= 70

    print(f"  Verdicts: real={n_real}, unsure={n_unsure}, AI-generated={n_ai}")
    print(f"  Turing pass rate: {turing_pass_rate:.1f}% (target >= 70%)")
    print(f"  Mean coverage:    {mean_coverage:.1f}%")
    print(f"  Mean authenticity: {mean_authenticity:.2f}/5")
    print(f"  Hypothesis pass:  {hypothesis_pass}")

    # ---- Write outputs ----
    total_cost = sum(r.get("cost_usd", 0) for r in persona_results)

    summary = {
        "experiment_id": "6.21",
        "branch": "exp-6.21-population-turing-test",
        "model": model,
        "n_personas": len(personas),
        "n_raters": N_RATERS,
        "n_valid_judgments": len(valid_judgments),
        "verdicts": {
            "real": n_real,
            "unsure": n_unsure,
            "AI-generated": n_ai,
        },
        "turing_pass_rate_pct": turing_pass_rate,
        "mean_perceived_coverage_pct": mean_coverage,
        "mean_authenticity": mean_authenticity,
        "hypothesis": {
            "description": "Persona set passes population Turing test >= 70% of the time",
            "target_pass_rate_pct": 70,
            "actual_pass_rate_pct": turing_pass_rate,
            "pass": hypothesis_pass,
        },
        "total_cost_usd": total_cost,
        "judgments": valid_judgments,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "summary.json").write_text(json.dumps(summary, indent=2))
    (OUTPUT_DIR / "personas.json").write_text(
        json.dumps([r for r in persona_results if r["status"] == "ok"], indent=2, default=str)
    )

    # ---- Print summary ----
    print("\n" + "=" * 72)
    print("SUMMARY")
    print("=" * 72)
    print(json.dumps(summary, indent=2))
    print(f"\nArtifacts: {OUTPUT_DIR}/")


if __name__ == "__main__":
    asyncio.run(main())
