"""Claude-Code-Version Pipeline Runner.

Replicates the full pipeline architecture but uses Claude Code agents
as the LLM instead of the Anthropic SDK. No API key required.

Usage — run from Claude Code agent context:
    1. Agent runs prepare_clusters() to execute stages 1-2 (pure Python)
    2. Agent reads cluster data + system prompt, generates persona JSON itself
    3. Agent calls validate_persona() to check schema + groundedness
    4. Agent generates twin reply itself using the persona system prompt
    5. Agent calls persist_results() to write output

This script provides the Python scaffolding. The Claude Code agent
provides the LLM inference.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
for pkg in ("crawler", "segmentation", "synthesis", "orchestration", "twin", "evaluation"):
    sys.path.insert(0, str(REPO_ROOT / pkg))

OUTPUT_DIR = REPO_ROOT / "output"
CLUSTERS_DIR = OUTPUT_DIR / "clusters"

TENANT_ID = "tenant_acme_corp"
TENANT_INDUSTRY = "B2B SaaS"
TENANT_PRODUCT = "Project management tool for engineering teams"


def prepare_clusters() -> list[dict]:
    """Stage 1 (ingest) + Stage 2 (segment). Pure Python, no API calls.

    Returns cluster dicts and saves them to output/clusters/*.json
    for the Claude Code agent to read.
    """
    from crawler import fetch_all
    from segmentation.models.record import RawRecord
    from segmentation.pipeline import segment
    from synthesis.models.cluster import ClusterData

    # Stage 1: Ingest
    crawler_records = fetch_all(TENANT_ID)
    records = [RawRecord.model_validate(r.model_dump()) for r in crawler_records]
    print(f"[ingest] Fetched {len(records)} records for {TENANT_ID}")

    # Stage 2: Segment
    cluster_dicts = segment(
        records,
        tenant_industry=TENANT_INDUSTRY,
        tenant_product=TENANT_PRODUCT,
        existing_persona_names=[],
        similarity_threshold=0.15,
        min_cluster_size=2,
    )
    clusters = [ClusterData.model_validate(c) for c in cluster_dicts]
    print(f"[segment] Found {len(clusters)} clusters")

    # Save clusters for the agent to read
    CLUSTERS_DIR.mkdir(parents=True, exist_ok=True)
    saved = []
    for i, cluster in enumerate(clusters):
        cluster_dict = cluster.model_dump(mode="json")
        path = CLUSTERS_DIR / f"cluster_{i:02d}.json"
        path.write_text(json.dumps(cluster_dict, indent=2, default=str))
        saved.append(cluster_dict)
        print(f"  cluster_{i:02d}: {cluster.cluster_id} ({cluster.summary.cluster_size} records)")

    return saved


def get_system_prompt(exclude_sections: set[str] | None = None) -> str:
    """Get the synthesis system prompt for the agent to use."""
    from synthesis.engine.prompt_builder import build_system_prompt
    return build_system_prompt(exclude_sections=exclude_sections)


def get_user_message(cluster_dict: dict, exclude_sections: set[str] | None = None) -> str:
    """Get the formatted user message for a cluster."""
    from synthesis.engine.prompt_builder import build_user_message
    from synthesis.models.cluster import ClusterData
    cluster = ClusterData.model_validate(cluster_dict)
    return build_user_message(cluster, exclude_sections=exclude_sections)


def get_persona_schema() -> dict:
    """Get the PersonaV1 JSON schema the agent must conform to."""
    from synthesis.models.persona import PersonaV1
    return PersonaV1.model_json_schema()


def validate_persona(persona_json: dict, cluster_dict: dict) -> dict:
    """Validate a persona dict against PersonaV1 schema + groundedness.

    Args:
        persona_json: The persona dict generated by the agent
        cluster_dict: The cluster dict the persona was generated from

    Returns:
        {
            "valid": bool,
            "persona": dict or None,
            "groundedness_score": float,
            "groundedness_passed": bool,
            "violations": list[str],
            "validation_errors": list[str],
        }
    """
    from pydantic import ValidationError
    from synthesis.models.persona import PersonaV1
    from synthesis.models.cluster import ClusterData
    from synthesis.engine.groundedness import check_groundedness

    result = {
        "valid": False,
        "persona": None,
        "groundedness_score": 0.0,
        "groundedness_passed": False,
        "violations": [],
        "validation_errors": [],
    }

    # Schema validation
    try:
        persona = PersonaV1.model_validate(persona_json)
    except ValidationError as e:
        result["validation_errors"] = [
            f"{err['loc']}: {err['msg']}" for err in e.errors()
        ]
        return result

    # Groundedness check
    cluster = ClusterData.model_validate(cluster_dict)
    report = check_groundedness(persona, cluster)

    result["valid"] = True
    result["persona"] = persona.model_dump(mode="json")
    result["groundedness_score"] = report.score
    result["groundedness_passed"] = report.passed
    result["violations"] = report.violations

    return result


def get_twin_system_prompt(persona_dict: dict) -> str:
    """Get the twin system prompt for the agent to use in character."""
    from twin.chat import build_persona_system_prompt
    return build_persona_system_prompt(persona_dict)


def persist_results(personas: list[dict]) -> list[Path]:
    """Stage 5: Write persona results to output/*.json.

    Args:
        personas: list of dicts with keys:
            - cluster_id
            - persona (the PersonaV1 dict)
            - groundedness (float score)
            - cost_usd (0.0 for claude-code-version)
            - attempts (int)
            - twin_demo_reply (str, optional)

    Returns:
        list of paths written
    """
    OUTPUT_DIR.mkdir(exist_ok=True)
    paths = []
    for i, entry in enumerate(personas):
        path = OUTPUT_DIR / f"persona_{i:02d}.json"
        path.write_text(json.dumps(entry, indent=2, default=str))
        paths.append(path)
        print(f"  Wrote {path}")
    print(f"[persist] Saved {len(personas)} personas to {OUTPUT_DIR}/")
    return paths


# ---------------------------------------------------------------------------
# Convenience: print everything the agent needs in one shot
# ---------------------------------------------------------------------------

def print_synthesis_context(cluster_index: int = 0) -> None:
    """Print the full synthesis context for a specific cluster.

    The agent reads this output, generates the persona JSON, then
    calls validate_persona() with the result.
    """
    cluster_files = sorted(CLUSTERS_DIR.glob("cluster_*.json"))
    if not cluster_files:
        print("ERROR: No clusters found. Run prepare_clusters() first.")
        return
    if cluster_index >= len(cluster_files):
        print(f"ERROR: Only {len(cluster_files)} clusters available.")
        return

    cluster_dict = json.loads(cluster_files[cluster_index].read_text())
    system_prompt = get_system_prompt()
    user_message = get_user_message(cluster_dict)
    schema = get_persona_schema()

    print("=" * 72)
    print(f"SYNTHESIS CONTEXT — Cluster {cluster_index}")
    print("=" * 72)
    print("\n## SYSTEM PROMPT\n")
    print(system_prompt)
    print("\n## USER MESSAGE\n")
    print(user_message)
    print("\n## OUTPUT SCHEMA\n")
    print(json.dumps(schema, indent=2))
    print("\n" + "=" * 72)
    print("Generate a JSON object conforming to the schema above.")
    print("=" * 72)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["prepare", "context", "schema", "validate"])
    parser.add_argument("--cluster", type=int, default=0)
    parser.add_argument("--persona-file", type=str, help="Path to persona JSON for validation")
    args = parser.parse_args()

    if args.command == "prepare":
        prepare_clusters()
    elif args.command == "context":
        print_synthesis_context(args.cluster)
    elif args.command == "schema":
        print(json.dumps(get_persona_schema(), indent=2))
    elif args.command == "validate":
        if not args.persona_file:
            print("ERROR: --persona-file required for validate command")
            sys.exit(1)
        persona = json.loads(Path(args.persona_file).read_text())
        cluster_file = sorted(CLUSTERS_DIR.glob("cluster_*.json"))[args.cluster]
        cluster = json.loads(cluster_file.read_text())
        result = validate_persona(persona, cluster)
        print(json.dumps(result, indent=2))
