"""exp-6.21 — Population-level Turing test.

Baseline vs Treatment: present two persona sets to LLM judges:
  - Baseline: personas from sparse clusters (3 records each)
  - Treatment: personas from full clusters

Hypothesis: Treatment set passes the population Turing test >= 70% of the
time, while baseline passes <= 40%.

Usage:
    python scripts/run_exp_6_21.py
"""

from __future__ import annotations

import asyncio
import json
import random
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "crawler"))
sys.path.insert(0, str(REPO_ROOT / "segmentation"))
sys.path.insert(0, str(REPO_ROOT / "synthesis"))
sys.path.insert(0, str(REPO_ROOT / "orchestration"))

from dotenv import load_dotenv

load_dotenv(REPO_ROOT / "synthesis" / ".env")

from anthropic import AsyncAnthropic  # noqa: E402

from crawler import fetch_all  # noqa: E402
from segmentation.models.record import RawRecord  # noqa: E402
from segmentation.pipeline import segment  # noqa: E402
from synthesis.config import settings  # noqa: E402
from synthesis.engine.model_backend import AnthropicBackend  # noqa: E402
from synthesis.engine.synthesizer import SynthesisError, synthesize  # noqa: E402
from synthesis.models.cluster import ClusterData  # noqa: E402

TENANT_ID = "tenant_acme_corp"
TENANT_INDUSTRY = "B2B SaaS"
TENANT_PRODUCT = "Project management tool for engineering teams"
OUTPUT_DIR = REPO_ROOT / "output" / "experiments" / "exp-6.21"

N_RATERS = 10


def subsample_cluster(cluster: ClusterData, target_size: int, seed: int = 42) -> ClusterData:
    records = list(cluster.sample_records)
    if len(records) <= target_size:
        return cluster
    rng = random.Random(seed)
    sample = rng.sample(records, target_size)
    sub = cluster.model_copy(deep=True)
    sub.sample_records = sample
    sub.summary.cluster_size = target_size
    sub.cluster_id = f"{cluster.cluster_id}_n{target_size}"
    return sub


async def judge_population(personas, client, model, rater_id, condition_label):
    persona_cards = []
    for i, p in enumerate(personas):
        card = f"""### Persona {i + 1}: {p.get('name')}
Summary: {p.get('summary')}
Goals: {', '.join(p.get('goals', [])[:3])}
Pains: {', '.join(p.get('pains', [])[:3])}
Vocabulary: {', '.join(p.get('vocabulary', [])[:5])}
Sample quote: "{p.get('sample_quotes', [''])[0]}"
"""
        persona_cards.append(card)

    all_cards = "\n".join(persona_cards)

    prompt = f"""You are Evaluator #{rater_id} reviewing a set of customer personas for a B2B SaaS company that makes project management tools for engineering teams.

Below is the complete persona set. These personas were either (A) created from real customer behavioral data, or (B) generated by an AI system.

{all_cards}

Answer these three questions:

1. Does this set represent a real company's customer base, or was it AI-generated? Answer: "real", "AI-generated", or "unsure"
2. What percentage of a real customer base for this type of product does this set appear to cover? (0-100)
3. Rate the overall authenticity of this persona set (1-5, where 5 = completely believable as real customers)

Respond with STRICT JSON only:
{{"verdict": "real" or "AI-generated" or "unsure", "coverage_pct": <int 0-100>, "authenticity": <int 1-5>, "rationale": "<2-3 sentences>"}}"""

    resp = await client.messages.create(
        model=model, max_tokens=300, temperature=0.8,
        messages=[{"role": "user", "content": prompt}],
    )
    text = next(b.text for b in resp.content if b.type == "text")
    match = re.search(r"\{.*\}", text, re.DOTALL)
    return json.loads(match.group(0)) if match else {}


def compute_turing_metrics(judgments):
    valid = [j for j in judgments if j]
    n_real = sum(1 for j in valid if j.get("verdict") == "real")
    n_unsure = sum(1 for j in valid if j.get("verdict") == "unsure")
    n_ai = sum(1 for j in valid if j.get("verdict") == "AI-generated")
    pass_rate = (n_real / len(valid) * 100) if valid else 0
    coverages = [j.get("coverage_pct", 0) for j in valid if "coverage_pct" in j]
    auths = [j.get("authenticity", 0) for j in valid if "authenticity" in j]
    return {
        "n_valid": len(valid),
        "verdicts": {"real": n_real, "unsure": n_unsure, "AI-generated": n_ai},
        "turing_pass_rate_pct": pass_rate,
        "mean_coverage_pct": sum(coverages) / len(coverages) if coverages else 0,
        "mean_authenticity": sum(auths) / len(auths) if auths else 0,
        "judgments": valid,
    }


async def main():
    print("=" * 72)
    print("exp-6.21 — Population-level Turing test (baseline vs treatment)")
    print("=" * 72)

    if not settings.anthropic_api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not set")

    client = AsyncAnthropic(api_key=settings.anthropic_api_key)
    backend = AnthropicBackend(client=client, model=settings.default_model)
    model = settings.default_model

    # ---- Step 1: Fetch + segment ----
    print("\n[1/5] Fetching and segmenting...")
    raw_records = fetch_all(TENANT_ID)
    records = [RawRecord.model_validate(r.model_dump()) for r in raw_records]
    cluster_dicts = segment(
        records, tenant_industry=TENANT_INDUSTRY, tenant_product=TENANT_PRODUCT,
        existing_persona_names=[], similarity_threshold=0.15, min_cluster_size=2,
    )
    clusters = sorted(
        [ClusterData.model_validate(c) for c in cluster_dicts],
        key=lambda c: c.cluster_id,
    )
    print(f"  Got {len(clusters)} clusters")

    # ---- Step 2: Synthesize baseline set (sparse 3-record clusters) ----
    print("\n[2/5] Synthesizing baseline set (sparse, 3 records per cluster)...")
    baseline_personas = []
    baseline_cost = 0.0
    for i, cluster in enumerate(clusters):
        sparse = subsample_cluster(cluster, 3)
        print(f"  [{i+1}/{len(clusters)}] {sparse.cluster_id}...")
        try:
            r = await synthesize(sparse, backend, max_retries=4)
            p = r.persona.model_dump(mode="json")
            baseline_personas.append(p)
            baseline_cost += r.total_cost_usd
            print(f"    [OK] {p['name']}  cost=${r.total_cost_usd:.4f}")
        except SynthesisError as e:
            baseline_cost += sum(a.cost_usd for a in e.attempts)
            print(f"    [FAIL] {e}")

    # ---- Step 3: Synthesize treatment set (full clusters) ----
    print("\n[3/5] Synthesizing treatment set (full clusters)...")
    treatment_personas = []
    treatment_cost = 0.0
    for i, cluster in enumerate(clusters):
        print(f"  [{i+1}/{len(clusters)}] {cluster.cluster_id}...")
        try:
            r = await synthesize(cluster, backend, max_retries=4)
            p = r.persona.model_dump(mode="json")
            treatment_personas.append(p)
            treatment_cost += r.total_cost_usd
            print(f"    [OK] {p['name']}  cost=${r.total_cost_usd:.4f}")
        except SynthesisError as e:
            treatment_cost += sum(a.cost_usd for a in e.attempts)
            print(f"    [FAIL] {e}")

    if not baseline_personas or not treatment_personas:
        raise RuntimeError("Need at least 1 persona per condition")

    # ---- Step 4: Judge both sets ----
    print(f"\n[4/5] Judging baseline set ({len(baseline_personas)} personas) with {N_RATERS} raters...")
    baseline_judgments = await asyncio.gather(*[
        judge_population(baseline_personas, client, model, rid, "baseline")
        for rid in range(1, N_RATERS + 1)
    ])
    baseline_metrics = compute_turing_metrics(baseline_judgments)
    print(f"  Baseline: pass_rate={baseline_metrics['turing_pass_rate_pct']:.0f}%  "
          f"auth={baseline_metrics['mean_authenticity']:.1f}  "
          f"coverage={baseline_metrics['mean_coverage_pct']:.0f}%")

    print(f"\n  Judging treatment set ({len(treatment_personas)} personas) with {N_RATERS} raters...")
    treatment_judgments = await asyncio.gather(*[
        judge_population(treatment_personas, client, model, rid, "treatment")
        for rid in range(1, N_RATERS + 1)
    ])
    treatment_metrics = compute_turing_metrics(treatment_judgments)
    print(f"  Treatment: pass_rate={treatment_metrics['turing_pass_rate_pct']:.0f}%  "
          f"auth={treatment_metrics['mean_authenticity']:.1f}  "
          f"coverage={treatment_metrics['mean_coverage_pct']:.0f}%")

    # ---- Step 5: Compare ----
    print("\n[5/5] Comparing...")
    b_pass = baseline_metrics["turing_pass_rate_pct"]
    t_pass = treatment_metrics["turing_pass_rate_pct"]
    delta_pass = t_pass - b_pass
    hypothesis_pass = t_pass >= 70

    summary = {
        "experiment_id": "6.21",
        "branch": "exp-6.21-population-turing-test",
        "model": model,
        "baseline": {
            "condition": "sparse (3 records per cluster)",
            "n_personas": len(baseline_personas),
            "persona_names": [p["name"] for p in baseline_personas],
            **{k: v for k, v in baseline_metrics.items() if k != "judgments"},
        },
        "treatment": {
            "condition": "full clusters",
            "n_personas": len(treatment_personas),
            "persona_names": [p["name"] for p in treatment_personas],
            **{k: v for k, v in treatment_metrics.items() if k != "judgments"},
        },
        "delta_pass_rate_pct": delta_pass,
        "delta_authenticity": treatment_metrics["mean_authenticity"] - baseline_metrics["mean_authenticity"],
        "delta_coverage_pct": treatment_metrics["mean_coverage_pct"] - baseline_metrics["mean_coverage_pct"],
        "hypothesis": {
            "description": "Treatment set passes population Turing test >= 70%",
            "target_pass_rate_pct": 70,
            "actual_treatment_pass_rate_pct": t_pass,
            "actual_baseline_pass_rate_pct": b_pass,
            "pass": hypothesis_pass,
        },
        "total_cost_usd": baseline_cost + treatment_cost,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "summary.json").write_text(json.dumps(summary, indent=2))
    (OUTPUT_DIR / "personas.json").write_text(json.dumps({
        "baseline": [{"persona": p} for p in baseline_personas],
        "treatment": [{"persona": p} for p in treatment_personas],
    }, indent=2, default=str))
    (OUTPUT_DIR / "judgments.json").write_text(json.dumps({
        "baseline": baseline_metrics["judgments"],
        "treatment": treatment_metrics["judgments"],
    }, indent=2, default=str))

    print("\n" + "=" * 72)
    print("SUMMARY")
    print("=" * 72)
    print(json.dumps(summary, indent=2))
    print(f"\nArtifacts: {OUTPUT_DIR}/")


if __name__ == "__main__":
    asyncio.run(main())
